services:
  baikal:
    image: ckulka/baikal:0.9.5-nginx
    container_name: baikal
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./baikal/config:/var/www/baikal/config
      - ./baikal/data:/var/www/baifal/Specific
