services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "8080:80"
    volumes:
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
      #library folder 
      - ./books:/books
    environment:
      - "TZ=Europe/Berlin"
    restart: unless-stopped
