services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:1.24.3
    ports: 
      - "8080:80"
    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data
      - ./freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - "TZ=Europe/Berlin"
      - "CRON_MIN=1,31"
    restart: unless-stopped
